#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Main")]
	public partial class ShipmentFeedDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOrder(Order instance);
    partial void UpdateOrder(Order instance);
    partial void DeleteOrder(Order instance);
    partial void InsertTracking(Tracking instance);
    partial void UpdateTracking(Tracking instance);
    partial void DeleteTracking(Tracking instance);
    #endregion
		
		public ShipmentFeedDataContext() : 
				base(global::Data.Properties.Settings.Default.MainConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ShipmentFeedDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShipmentFeedDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShipmentFeedDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShipmentFeedDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Order> Orders
		{
			get
			{
				return this.GetTable<Order>();
			}
		}
		
		public System.Data.Linq.Table<Tracking> Trackings
		{
			get
			{
				return this.GetTable<Tracking>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Orders")]
	public partial class Order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderNumber;
		
		private string _OrderSource;
		
		private System.Nullable<System.DateTime> _OrderDate;
		
		private System.Nullable<int> _CustomerID;
		
		private string _Name;
		
		private string _Company;
		
		private string _Email;
		
		private string _Address;
		
		private string _Address2;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private string _Country;
		
		private string _Phone;
		
		private string _PhoneExt;
		
		private string _ShipName;
		
		private string _ShipCompany;
		
		private string _ShipAddress;
		
		private string _ShipAddress2;
		
		private string _ShipCity;
		
		private string _ShipState;
		
		private string _ShipZip;
		
		private string _ShipCountry;
		
		private string _ShipEmail;
		
		private string _ShipPhone;
		
		private string _ShipPhoneExt;
		
		private string _Comments;
		
		private System.Nullable<decimal> _ProductTotal;
		
		private System.Nullable<decimal> _TaxTotal;
		
		private System.Nullable<decimal> _ShippingTotal;
		
		private System.Nullable<decimal> _GrandTotal;
		
		private string _Shipping;
		
		private System.Nullable<double> _ShippedWeight;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _SourceOrderID;
		
		private System.Nullable<byte> _FulfillmentStatus;
		
		private System.Nullable<int> _FulfillmentBatchID;
		
		private string _ManualReason;
		
		private System.Nullable<System.DateTime> _DateTimeFinalized;
		
		private string _CC_TransactionID;
		
		private string _CC_ProcessorResponseCode;
		
		private System.Nullable<bool> _Cancelled;
		
		private bool _Manual;
		
		private bool _ManualReady;
		
		private System.Nullable<int> _TokenID;
		
		private System.Nullable<int> _BillingID;
		
		private System.Nullable<int> _ShippingID;
		
		private System.Nullable<bool> _CS_Final;
		
		private System.Nullable<bool> _MultipleReady;
		
		private System.Nullable<System.DateTime> _DateCanceled;
		
		private string _IP;
		
		private string _RefererUrl;
		
		private EntitySet<Tracking> _Trackings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderNumberChanging(int value);
    partial void OnOrderNumberChanged();
    partial void OnOrderSourceChanging(string value);
    partial void OnOrderSourceChanged();
    partial void OnOrderDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOrderDateChanged();
    partial void OnCustomerIDChanging(System.Nullable<int> value);
    partial void OnCustomerIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnPhoneExtChanging(string value);
    partial void OnPhoneExtChanged();
    partial void OnShipNameChanging(string value);
    partial void OnShipNameChanged();
    partial void OnShipCompanyChanging(string value);
    partial void OnShipCompanyChanged();
    partial void OnShipAddressChanging(string value);
    partial void OnShipAddressChanged();
    partial void OnShipAddress2Changing(string value);
    partial void OnShipAddress2Changed();
    partial void OnShipCityChanging(string value);
    partial void OnShipCityChanged();
    partial void OnShipStateChanging(string value);
    partial void OnShipStateChanged();
    partial void OnShipZipChanging(string value);
    partial void OnShipZipChanged();
    partial void OnShipCountryChanging(string value);
    partial void OnShipCountryChanged();
    partial void OnShipEmailChanging(string value);
    partial void OnShipEmailChanged();
    partial void OnShipPhoneChanging(string value);
    partial void OnShipPhoneChanged();
    partial void OnShipPhoneExtChanging(string value);
    partial void OnShipPhoneExtChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnProductTotalChanging(System.Nullable<decimal> value);
    partial void OnProductTotalChanged();
    partial void OnTaxTotalChanging(System.Nullable<decimal> value);
    partial void OnTaxTotalChanged();
    partial void OnShippingTotalChanging(System.Nullable<decimal> value);
    partial void OnShippingTotalChanged();
    partial void OnGrandTotalChanging(System.Nullable<decimal> value);
    partial void OnGrandTotalChanged();
    partial void OnShippingChanging(string value);
    partial void OnShippingChanged();
    partial void OnShippedWeightChanging(System.Nullable<double> value);
    partial void OnShippedWeightChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnSourceOrderIDChanging(string value);
    partial void OnSourceOrderIDChanged();
    partial void OnFulfillmentStatusChanging(System.Nullable<byte> value);
    partial void OnFulfillmentStatusChanged();
    partial void OnFulfillmentBatchIDChanging(System.Nullable<int> value);
    partial void OnFulfillmentBatchIDChanged();
    partial void OnManualReasonChanging(string value);
    partial void OnManualReasonChanged();
    partial void OnDateTimeFinalizedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeFinalizedChanged();
    partial void OnCC_TransactionIDChanging(string value);
    partial void OnCC_TransactionIDChanged();
    partial void OnCC_ProcessorResponseCodeChanging(string value);
    partial void OnCC_ProcessorResponseCodeChanged();
    partial void OnCancelledChanging(System.Nullable<bool> value);
    partial void OnCancelledChanged();
    partial void OnManualChanging(bool value);
    partial void OnManualChanged();
    partial void OnManualReadyChanging(bool value);
    partial void OnManualReadyChanged();
    partial void OnTokenIDChanging(System.Nullable<int> value);
    partial void OnTokenIDChanged();
    partial void OnBillingIDChanging(System.Nullable<int> value);
    partial void OnBillingIDChanged();
    partial void OnShippingIDChanging(System.Nullable<int> value);
    partial void OnShippingIDChanged();
    partial void OnCS_FinalChanging(System.Nullable<bool> value);
    partial void OnCS_FinalChanged();
    partial void OnMultipleReadyChanging(System.Nullable<bool> value);
    partial void OnMultipleReadyChanged();
    partial void OnDateCanceledChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCanceledChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnRefererUrlChanging(string value);
    partial void OnRefererUrlChanged();
    #endregion
		
		public Order()
		{
			this._Trackings = new EntitySet<Tracking>(new Action<Tracking>(this.attach_Trackings), new Action<Tracking>(this.detach_Trackings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNumber", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderNumber
		{
			get
			{
				return this._OrderNumber;
			}
			set
			{
				if ((this._OrderNumber != value))
				{
					this.OnOrderNumberChanging(value);
					this.SendPropertyChanging();
					this._OrderNumber = value;
					this.SendPropertyChanged("OrderNumber");
					this.OnOrderNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderSource", DbType="Char(2)")]
		public string OrderSource
		{
			get
			{
				return this._OrderSource;
			}
			set
			{
				if ((this._OrderSource != value))
				{
					this.OnOrderSourceChanging(value);
					this.SendPropertyChanging();
					this._OrderSource = value;
					this.SendPropertyChanged("OrderSource");
					this.OnOrderSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OrderDate
		{
			get
			{
				return this._OrderDate;
			}
			set
			{
				if ((this._OrderDate != value))
				{
					this.OnOrderDateChanging(value);
					this.SendPropertyChanging();
					this._OrderDate = value;
					this.SendPropertyChanged("OrderDate");
					this.OnOrderDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
		public System.Nullable<int> CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this.OnCustomerIDChanging(value);
					this.SendPropertyChanging();
					this._CustomerID = value;
					this.SendPropertyChanged("CustomerID");
					this.OnCustomerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(75)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="VarChar(255)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(255)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(255)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="VarChar(255)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(255)")]
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				if ((this._Country != value))
				{
					this.OnCountryChanging(value);
					this.SendPropertyChanging();
					this._Country = value;
					this.SendPropertyChanged("Country");
					this.OnCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(255)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneExt", DbType="VarChar(50)")]
		public string PhoneExt
		{
			get
			{
				return this._PhoneExt;
			}
			set
			{
				if ((this._PhoneExt != value))
				{
					this.OnPhoneExtChanging(value);
					this.SendPropertyChanging();
					this._PhoneExt = value;
					this.SendPropertyChanged("PhoneExt");
					this.OnPhoneExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipName", DbType="NVarChar(255)")]
		public string ShipName
		{
			get
			{
				return this._ShipName;
			}
			set
			{
				if ((this._ShipName != value))
				{
					this.OnShipNameChanging(value);
					this.SendPropertyChanging();
					this._ShipName = value;
					this.SendPropertyChanged("ShipName");
					this.OnShipNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCompany", DbType="VarChar(255)")]
		public string ShipCompany
		{
			get
			{
				return this._ShipCompany;
			}
			set
			{
				if ((this._ShipCompany != value))
				{
					this.OnShipCompanyChanging(value);
					this.SendPropertyChanging();
					this._ShipCompany = value;
					this.SendPropertyChanged("ShipCompany");
					this.OnShipCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipAddress", DbType="VarChar(255)")]
		public string ShipAddress
		{
			get
			{
				return this._ShipAddress;
			}
			set
			{
				if ((this._ShipAddress != value))
				{
					this.OnShipAddressChanging(value);
					this.SendPropertyChanging();
					this._ShipAddress = value;
					this.SendPropertyChanged("ShipAddress");
					this.OnShipAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipAddress2", DbType="VarChar(255)")]
		public string ShipAddress2
		{
			get
			{
				return this._ShipAddress2;
			}
			set
			{
				if ((this._ShipAddress2 != value))
				{
					this.OnShipAddress2Changing(value);
					this.SendPropertyChanging();
					this._ShipAddress2 = value;
					this.SendPropertyChanged("ShipAddress2");
					this.OnShipAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCity", DbType="VarChar(255)")]
		public string ShipCity
		{
			get
			{
				return this._ShipCity;
			}
			set
			{
				if ((this._ShipCity != value))
				{
					this.OnShipCityChanging(value);
					this.SendPropertyChanging();
					this._ShipCity = value;
					this.SendPropertyChanged("ShipCity");
					this.OnShipCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipState", DbType="VarChar(255)")]
		public string ShipState
		{
			get
			{
				return this._ShipState;
			}
			set
			{
				if ((this._ShipState != value))
				{
					this.OnShipStateChanging(value);
					this.SendPropertyChanging();
					this._ShipState = value;
					this.SendPropertyChanged("ShipState");
					this.OnShipStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipZip", DbType="VarChar(255)")]
		public string ShipZip
		{
			get
			{
				return this._ShipZip;
			}
			set
			{
				if ((this._ShipZip != value))
				{
					this.OnShipZipChanging(value);
					this.SendPropertyChanging();
					this._ShipZip = value;
					this.SendPropertyChanged("ShipZip");
					this.OnShipZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCountry", DbType="VarChar(255)")]
		public string ShipCountry
		{
			get
			{
				return this._ShipCountry;
			}
			set
			{
				if ((this._ShipCountry != value))
				{
					this.OnShipCountryChanging(value);
					this.SendPropertyChanging();
					this._ShipCountry = value;
					this.SendPropertyChanged("ShipCountry");
					this.OnShipCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipEmail", DbType="VarChar(255)")]
		public string ShipEmail
		{
			get
			{
				return this._ShipEmail;
			}
			set
			{
				if ((this._ShipEmail != value))
				{
					this.OnShipEmailChanging(value);
					this.SendPropertyChanging();
					this._ShipEmail = value;
					this.SendPropertyChanged("ShipEmail");
					this.OnShipEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPhone", DbType="VarChar(255)")]
		public string ShipPhone
		{
			get
			{
				return this._ShipPhone;
			}
			set
			{
				if ((this._ShipPhone != value))
				{
					this.OnShipPhoneChanging(value);
					this.SendPropertyChanging();
					this._ShipPhone = value;
					this.SendPropertyChanged("ShipPhone");
					this.OnShipPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPhoneExt", DbType="VarChar(50)")]
		public string ShipPhoneExt
		{
			get
			{
				return this._ShipPhoneExt;
			}
			set
			{
				if ((this._ShipPhoneExt != value))
				{
					this.OnShipPhoneExtChanging(value);
					this.SendPropertyChanging();
					this._ShipPhoneExt = value;
					this.SendPropertyChanged("ShipPhoneExt");
					this.OnShipPhoneExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductTotal", DbType="Money")]
		public System.Nullable<decimal> ProductTotal
		{
			get
			{
				return this._ProductTotal;
			}
			set
			{
				if ((this._ProductTotal != value))
				{
					this.OnProductTotalChanging(value);
					this.SendPropertyChanging();
					this._ProductTotal = value;
					this.SendPropertyChanged("ProductTotal");
					this.OnProductTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxTotal", DbType="Money")]
		public System.Nullable<decimal> TaxTotal
		{
			get
			{
				return this._TaxTotal;
			}
			set
			{
				if ((this._TaxTotal != value))
				{
					this.OnTaxTotalChanging(value);
					this.SendPropertyChanging();
					this._TaxTotal = value;
					this.SendPropertyChanged("TaxTotal");
					this.OnTaxTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingTotal", DbType="Money")]
		public System.Nullable<decimal> ShippingTotal
		{
			get
			{
				return this._ShippingTotal;
			}
			set
			{
				if ((this._ShippingTotal != value))
				{
					this.OnShippingTotalChanging(value);
					this.SendPropertyChanging();
					this._ShippingTotal = value;
					this.SendPropertyChanged("ShippingTotal");
					this.OnShippingTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrandTotal", DbType="Money")]
		public System.Nullable<decimal> GrandTotal
		{
			get
			{
				return this._GrandTotal;
			}
			set
			{
				if ((this._GrandTotal != value))
				{
					this.OnGrandTotalChanging(value);
					this.SendPropertyChanging();
					this._GrandTotal = value;
					this.SendPropertyChanged("GrandTotal");
					this.OnGrandTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipping", DbType="VarChar(255)")]
		public string Shipping
		{
			get
			{
				return this._Shipping;
			}
			set
			{
				if ((this._Shipping != value))
				{
					this.OnShippingChanging(value);
					this.SendPropertyChanging();
					this._Shipping = value;
					this.SendPropertyChanged("Shipping");
					this.OnShippingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippedWeight", DbType="Float")]
		public System.Nullable<double> ShippedWeight
		{
			get
			{
				return this._ShippedWeight;
			}
			set
			{
				if ((this._ShippedWeight != value))
				{
					this.OnShippedWeightChanging(value);
					this.SendPropertyChanging();
					this._ShippedWeight = value;
					this.SendPropertyChanged("ShippedWeight");
					this.OnShippedWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceOrderID", DbType="NVarChar(50)")]
		public string SourceOrderID
		{
			get
			{
				return this._SourceOrderID;
			}
			set
			{
				if ((this._SourceOrderID != value))
				{
					this.OnSourceOrderIDChanging(value);
					this.SendPropertyChanging();
					this._SourceOrderID = value;
					this.SendPropertyChanged("SourceOrderID");
					this.OnSourceOrderIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FulfillmentStatus", DbType="TinyInt")]
		public System.Nullable<byte> FulfillmentStatus
		{
			get
			{
				return this._FulfillmentStatus;
			}
			set
			{
				if ((this._FulfillmentStatus != value))
				{
					this.OnFulfillmentStatusChanging(value);
					this.SendPropertyChanging();
					this._FulfillmentStatus = value;
					this.SendPropertyChanged("FulfillmentStatus");
					this.OnFulfillmentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FulfillmentBatchID", DbType="Int")]
		public System.Nullable<int> FulfillmentBatchID
		{
			get
			{
				return this._FulfillmentBatchID;
			}
			set
			{
				if ((this._FulfillmentBatchID != value))
				{
					this.OnFulfillmentBatchIDChanging(value);
					this.SendPropertyChanging();
					this._FulfillmentBatchID = value;
					this.SendPropertyChanged("FulfillmentBatchID");
					this.OnFulfillmentBatchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManualReason", DbType="VarChar(50)")]
		public string ManualReason
		{
			get
			{
				return this._ManualReason;
			}
			set
			{
				if ((this._ManualReason != value))
				{
					this.OnManualReasonChanging(value);
					this.SendPropertyChanging();
					this._ManualReason = value;
					this.SendPropertyChanged("ManualReason");
					this.OnManualReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeFinalized", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeFinalized
		{
			get
			{
				return this._DateTimeFinalized;
			}
			set
			{
				if ((this._DateTimeFinalized != value))
				{
					this.OnDateTimeFinalizedChanging(value);
					this.SendPropertyChanging();
					this._DateTimeFinalized = value;
					this.SendPropertyChanged("DateTimeFinalized");
					this.OnDateTimeFinalizedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_TransactionID", DbType="VarChar(10)")]
		public string CC_TransactionID
		{
			get
			{
				return this._CC_TransactionID;
			}
			set
			{
				if ((this._CC_TransactionID != value))
				{
					this.OnCC_TransactionIDChanging(value);
					this.SendPropertyChanging();
					this._CC_TransactionID = value;
					this.SendPropertyChanged("CC_TransactionID");
					this.OnCC_TransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_ProcessorResponseCode", DbType="VarChar(10)")]
		public string CC_ProcessorResponseCode
		{
			get
			{
				return this._CC_ProcessorResponseCode;
			}
			set
			{
				if ((this._CC_ProcessorResponseCode != value))
				{
					this.OnCC_ProcessorResponseCodeChanging(value);
					this.SendPropertyChanging();
					this._CC_ProcessorResponseCode = value;
					this.SendPropertyChanged("CC_ProcessorResponseCode");
					this.OnCC_ProcessorResponseCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cancelled", DbType="Bit")]
		public System.Nullable<bool> Cancelled
		{
			get
			{
				return this._Cancelled;
			}
			set
			{
				if ((this._Cancelled != value))
				{
					this.OnCancelledChanging(value);
					this.SendPropertyChanging();
					this._Cancelled = value;
					this.SendPropertyChanged("Cancelled");
					this.OnCancelledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manual", DbType="Bit NOT NULL")]
		public bool Manual
		{
			get
			{
				return this._Manual;
			}
			set
			{
				if ((this._Manual != value))
				{
					this.OnManualChanging(value);
					this.SendPropertyChanging();
					this._Manual = value;
					this.SendPropertyChanged("Manual");
					this.OnManualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManualReady", DbType="Bit NOT NULL")]
		public bool ManualReady
		{
			get
			{
				return this._ManualReady;
			}
			set
			{
				if ((this._ManualReady != value))
				{
					this.OnManualReadyChanging(value);
					this.SendPropertyChanging();
					this._ManualReady = value;
					this.SendPropertyChanged("ManualReady");
					this.OnManualReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TokenID", DbType="Int")]
		public System.Nullable<int> TokenID
		{
			get
			{
				return this._TokenID;
			}
			set
			{
				if ((this._TokenID != value))
				{
					this.OnTokenIDChanging(value);
					this.SendPropertyChanging();
					this._TokenID = value;
					this.SendPropertyChanged("TokenID");
					this.OnTokenIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillingID", DbType="Int")]
		public System.Nullable<int> BillingID
		{
			get
			{
				return this._BillingID;
			}
			set
			{
				if ((this._BillingID != value))
				{
					this.OnBillingIDChanging(value);
					this.SendPropertyChanging();
					this._BillingID = value;
					this.SendPropertyChanged("BillingID");
					this.OnBillingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShippingID", DbType="Int")]
		public System.Nullable<int> ShippingID
		{
			get
			{
				return this._ShippingID;
			}
			set
			{
				if ((this._ShippingID != value))
				{
					this.OnShippingIDChanging(value);
					this.SendPropertyChanging();
					this._ShippingID = value;
					this.SendPropertyChanged("ShippingID");
					this.OnShippingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CS_Final", DbType="Bit")]
		public System.Nullable<bool> CS_Final
		{
			get
			{
				return this._CS_Final;
			}
			set
			{
				if ((this._CS_Final != value))
				{
					this.OnCS_FinalChanging(value);
					this.SendPropertyChanging();
					this._CS_Final = value;
					this.SendPropertyChanged("CS_Final");
					this.OnCS_FinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MultipleReady", DbType="Bit")]
		public System.Nullable<bool> MultipleReady
		{
			get
			{
				return this._MultipleReady;
			}
			set
			{
				if ((this._MultipleReady != value))
				{
					this.OnMultipleReadyChanging(value);
					this.SendPropertyChanging();
					this._MultipleReady = value;
					this.SendPropertyChanged("MultipleReady");
					this.OnMultipleReadyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCanceled", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCanceled
		{
			get
			{
				return this._DateCanceled;
			}
			set
			{
				if ((this._DateCanceled != value))
				{
					this.OnDateCanceledChanging(value);
					this.SendPropertyChanging();
					this._DateCanceled = value;
					this.SendPropertyChanged("DateCanceled");
					this.OnDateCanceledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(39)")]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefererUrl", DbType="VarChar(MAX)")]
		public string RefererUrl
		{
			get
			{
				return this._RefererUrl;
			}
			set
			{
				if ((this._RefererUrl != value))
				{
					this.OnRefererUrlChanging(value);
					this.SendPropertyChanging();
					this._RefererUrl = value;
					this.SendPropertyChanged("RefererUrl");
					this.OnRefererUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Order_Tracking", Storage="_Trackings", ThisKey="OrderNumber", OtherKey="OrderNum")]
		public EntitySet<Tracking> Trackings
		{
			get
			{
				return this._Trackings;
			}
			set
			{
				this._Trackings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Trackings(Tracking entity)
		{
			this.SendPropertyChanging();
			entity.Order = this;
		}
		
		private void detach_Trackings(Tracking entity)
		{
			this.SendPropertyChanging();
			entity.Order = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tracking")]
	public partial class Tracking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _OrderTrackingID;
		
		private int _OrderNum;
		
		private string _TrackingID;
		
		private string _PickupDate;
		
		private string _Carrier;
		
		private bool _EmailSent;
		
		private bool _StatusSent;
		
		private System.Nullable<System.DateTime> _DateAdded;
		
		private System.Nullable<int> _NumericKey;
		
		private bool _External;
		
		private string _Invoice;
		
		private System.Nullable<int> _ServiceTypeID;
		
		private bool _Sent;
		
		private EntityRef<Order> _Order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrderTrackingIDChanging(int value);
    partial void OnOrderTrackingIDChanged();
    partial void OnOrderNumChanging(int value);
    partial void OnOrderNumChanged();
    partial void OnTrackingIDChanging(string value);
    partial void OnTrackingIDChanged();
    partial void OnPickupDateChanging(string value);
    partial void OnPickupDateChanged();
    partial void OnCarrierChanging(string value);
    partial void OnCarrierChanged();
    partial void OnEmailSentChanging(bool value);
    partial void OnEmailSentChanged();
    partial void OnStatusSentChanging(bool value);
    partial void OnStatusSentChanged();
    partial void OnDateAddedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateAddedChanged();
    partial void OnNumericKeyChanging(System.Nullable<int> value);
    partial void OnNumericKeyChanged();
    partial void OnExternalChanging(bool value);
    partial void OnExternalChanged();
    partial void OnInvoiceChanging(string value);
    partial void OnInvoiceChanged();
    partial void OnServiceTypeIDChanging(System.Nullable<int> value);
    partial void OnServiceTypeIDChanged();
    partial void OnSentChanging(bool value);
    partial void OnSentChanged();
    #endregion
		
		public Tracking()
		{
			this._Order = default(EntityRef<Order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderTrackingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int OrderTrackingID
		{
			get
			{
				return this._OrderTrackingID;
			}
			set
			{
				if ((this._OrderTrackingID != value))
				{
					this.OnOrderTrackingIDChanging(value);
					this.SendPropertyChanging();
					this._OrderTrackingID = value;
					this.SendPropertyChanged("OrderTrackingID");
					this.OnOrderTrackingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderNum", DbType="Int NOT NULL")]
		public int OrderNum
		{
			get
			{
				return this._OrderNum;
			}
			set
			{
				if ((this._OrderNum != value))
				{
					if (this._Order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOrderNumChanging(value);
					this.SendPropertyChanging();
					this._OrderNum = value;
					this.SendPropertyChanged("OrderNum");
					this.OnOrderNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackingID", DbType="NVarChar(50)")]
		public string TrackingID
		{
			get
			{
				return this._TrackingID;
			}
			set
			{
				if ((this._TrackingID != value))
				{
					this.OnTrackingIDChanging(value);
					this.SendPropertyChanging();
					this._TrackingID = value;
					this.SendPropertyChanged("TrackingID");
					this.OnTrackingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PickupDate", DbType="NVarChar(25)")]
		public string PickupDate
		{
			get
			{
				return this._PickupDate;
			}
			set
			{
				if ((this._PickupDate != value))
				{
					this.OnPickupDateChanging(value);
					this.SendPropertyChanging();
					this._PickupDate = value;
					this.SendPropertyChanged("PickupDate");
					this.OnPickupDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrier", DbType="NVarChar(5)")]
		public string Carrier
		{
			get
			{
				return this._Carrier;
			}
			set
			{
				if ((this._Carrier != value))
				{
					this.OnCarrierChanging(value);
					this.SendPropertyChanging();
					this._Carrier = value;
					this.SendPropertyChanged("Carrier");
					this.OnCarrierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSent", DbType="Bit NOT NULL")]
		public bool EmailSent
		{
			get
			{
				return this._EmailSent;
			}
			set
			{
				if ((this._EmailSent != value))
				{
					this.OnEmailSentChanging(value);
					this.SendPropertyChanging();
					this._EmailSent = value;
					this.SendPropertyChanged("EmailSent");
					this.OnEmailSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusSent", DbType="Bit NOT NULL")]
		public bool StatusSent
		{
			get
			{
				return this._StatusSent;
			}
			set
			{
				if ((this._StatusSent != value))
				{
					this.OnStatusSentChanging(value);
					this.SendPropertyChanging();
					this._StatusSent = value;
					this.SendPropertyChanged("StatusSent");
					this.OnStatusSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumericKey", DbType="Int")]
		public System.Nullable<int> NumericKey
		{
			get
			{
				return this._NumericKey;
			}
			set
			{
				if ((this._NumericKey != value))
				{
					this.OnNumericKeyChanging(value);
					this.SendPropertyChanging();
					this._NumericKey = value;
					this.SendPropertyChanged("NumericKey");
					this.OnNumericKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[External]", Storage="_External", DbType="Bit NOT NULL")]
		public bool External
		{
			get
			{
				return this._External;
			}
			set
			{
				if ((this._External != value))
				{
					this.OnExternalChanging(value);
					this.SendPropertyChanging();
					this._External = value;
					this.SendPropertyChanged("External");
					this.OnExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice", DbType="NVarChar(50)")]
		public string Invoice
		{
			get
			{
				return this._Invoice;
			}
			set
			{
				if ((this._Invoice != value))
				{
					this.OnInvoiceChanging(value);
					this.SendPropertyChanging();
					this._Invoice = value;
					this.SendPropertyChanged("Invoice");
					this.OnInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceTypeID", DbType="Int")]
		public System.Nullable<int> ServiceTypeID
		{
			get
			{
				return this._ServiceTypeID;
			}
			set
			{
				if ((this._ServiceTypeID != value))
				{
					this.OnServiceTypeIDChanging(value);
					this.SendPropertyChanging();
					this._ServiceTypeID = value;
					this.SendPropertyChanged("ServiceTypeID");
					this.OnServiceTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sent", DbType="Bit NOT NULL")]
		public bool Sent
		{
			get
			{
				return this._Sent;
			}
			set
			{
				if ((this._Sent != value))
				{
					this.OnSentChanging(value);
					this.SendPropertyChanging();
					this._Sent = value;
					this.SendPropertyChanged("Sent");
					this.OnSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Order_Tracking", Storage="_Order", ThisKey="OrderNum", OtherKey="OrderNumber", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Order Order
		{
			get
			{
				return this._Order.Entity;
			}
			set
			{
				Order previousValue = this._Order.Entity;
				if (((previousValue != value) 
							|| (this._Order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Order.Entity = null;
						previousValue.Trackings.Remove(this);
					}
					this._Order.Entity = value;
					if ((value != null))
					{
						value.Trackings.Add(this);
						this._OrderNum = value.OrderNumber;
					}
					else
					{
						this._OrderNum = default(int);
					}
					this.SendPropertyChanged("Order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
